---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-gpgme
    - python3-gpgme

- name: Add repository key
  apt_key:
    url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    state: present

- name: Add rabbitmq-server respository
  apt_repository:
    repo: deb https://dl.bintray.com/rabbitmq/debian stretch main
    state: present

- name: Add erlang respository
  apt_repository:
    repo: deb https://dl.bintray.com/rabbitmq/debian stretch erlang
    state: present

- name: Install RabbitMQ
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rabbitmq-server

- name: Enable RabbitMQ service
  service:
    name: rabbitmq-server
    enabled: yes
    state: started

- name: Remove defualt RabbitMQ user
  rabbitmq_user:
    user: guest
    state: absent

- name: Add Galaxy RabbitMQ vhost
  rabbitmq_vhost:
    name: "{{ rabbitmq_galaxy_vhost }}"
    state: present

- name: Add Galaxy RabbitMQ user
  rabbitmq_user:
    user: "{{ rabbitmq_galaxy_user_name }}"
    password: "{{ rabbitmq_galaxy_user_password }}"
    vhost: "{{ rabbitmq_galaxy_vhost }}"
    configure_priv: pulsar
    read_priv: pulsar
    write_priv: pulsar
    state: present

- name: Add admin RabbitMQ user
  rabbitmq_user:
    user: "{{ rabbitmq_admin_user_name }}"
    password: "{{ rabbitmq_admin_user_password }}"
    tags: administrator
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
      - vhost: "{{ rabbitmq_galaxy_vhost }}"
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present

- name: Enable RabbitMQ management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
