---
- name: Install apt dependencies
  package:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Install common packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - patch
    - lsof
    - screen
    - vim
    - git
    - iotop
    - iftop
    - htop
    - strace
